# Generated by Django 4.1.2 on 2024-06-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerremas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='cantidad',
        ),
    ]
