# Generated by Django 4.1.2 on 2024-06-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerremas', '0002_remove_articulo_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='articulo',
            new_name='articulos',
        ),
    ]
