# Generated by Django 4.1.2 on 2024-06-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerremas', '0003_rename_articulo_carrito_articulos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='articulos',
            new_name='productos',
        ),
    ]
