# Generated by Django 4.1.2 on 2025-05-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerremas', '0004_rename_articulos_carrito_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='id_api_producto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
